In [1]:
!pip install tensorflow


In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [9]:
tf.config.list_physical_devices('GPU')

[]

In [11]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13655387480601878904
xla_global_id: -1
]


In [15]:
a=tf.constant([1,2,3,4])  

In [17]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [19]:
a=tf.constant(1)  # Scalar
a=tf.constant([1,2,3,4]) # 1D array
a=tf.constant([[1,2,3],[4,5,6]]) #2d tensor
a=tf.constant([[[1,2],[3,4]],[[10,20],[30,40]],[[100,200],[300,400]]])

In [22]:
a.shape

TensorShape([3, 2, 2])

In [24]:
tf.shape(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 2], dtype=int32)>

In [26]:
a

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[  1,   2],
        [  3,   4]],

       [[ 10,  20],
        [ 30,  40]],

       [[100, 200],
        [300, 400]]], dtype=int32)>

In [28]:
a[0:1]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [30]:
a[1,0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [32]:
a[1,1,1]

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [70]:
b=tf.Variable([1,2,3,4,5],dtype=tf.float16)
b

<tf.Variable 'Variable:0' shape=(5,) dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>

In [44]:
b.assign([10,20,30,40,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

In [48]:
tf.ones((10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [50]:
tf.zeros((10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [54]:
tf.range(1,10,2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [60]:
tf.linspace(1,2,5)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1.  , 1.25, 1.5 , 1.75, 2.  ])>

In [62]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [104]:
tf.random.uniform((2,3),100,200,dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[199, 176, 125],
       [168, 121, 194]], dtype=int32)>

In [127]:
#tf.random.set_seed(5)
a=tf.random.uniform((2,3),100,200,dtype=tf.int32,seed=10)
#tf.random.set_seed(5)
b=tf.random.uniform((2,3),100,200,dtype=tf.int32,seed=11)


In [129]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[181, 101, 171],
       [151, 129, 184]], dtype=int32)>

In [131]:
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[110, 123, 197],
       [131, 121, 195]], dtype=int32)>

In [133]:
tf.random.normal((5,5),0,1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.2405608 ,  1.6238999 ,  2.3377132 , -0.3933    , -0.3198626 ],
       [-0.578736  ,  1.4116361 ,  0.21565276, -0.36463994, -0.6211336 ],
       [ 1.4747376 ,  1.0786322 , -1.6976302 , -1.7638533 , -0.4789571 ],
       [ 1.4693139 , -0.28912798,  0.73885906, -3.298254  ,  0.79898554],
       [-0.60034657,  0.2876222 ,  0.88191694, -0.5150032 ,  0.8985056 ]],
      dtype=float32)>

In [135]:
tf.random.shuffle(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[151, 129, 184],
       [181, 101, 171]], dtype=int32)>

In [138]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[181, 101, 171],
       [151, 129, 184]], dtype=int32)>

In [144]:
tf.reshape(a,(3,-1))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[181, 101],
       [171, 151],
       [129, 184]], dtype=int32)>

In [146]:
tf.reshape(a,(-1,))

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([181, 101, 171, 151, 129, 184], dtype=int32)>

In [238]:
a=tf.constant([1,2,3,4,5])
b=tf.constant([10,20,30,40,50])

In [240]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [242]:
b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

In [244]:
a+5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [246]:
a*5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 5, 10, 15, 20, 25], dtype=int32)>

In [248]:
a-5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-4, -3, -2, -1,  0], dtype=int32)>

In [250]:
a/5

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.2, 0.4, 0.6, 0.8, 1. ])>

In [252]:
a//5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 1], dtype=int32)>

In [254]:
a%5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 0], dtype=int32)>

In [258]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [262]:
a==5

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False,  True])>

In [264]:
tf.logical_and(a==5,b==50)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False,  True])>

In [266]:
a+b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 22, 33, 44, 55], dtype=int32)>

In [268]:
a-b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ -9, -18, -27, -36, -45], dtype=int32)>

In [272]:
a=tf.constant([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
tf.reduce_max(a,axis=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 6, 9, 3], dtype=int32)>

In [274]:
b=tf.constant([10,20,30])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [276]:
a+b

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [11, 22, 33]], dtype=int32)>

In [288]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[10,20],[30,40],[50,60]])


In [290]:
#tf.tensordot(a,b,1)

In [292]:
#tf.reduce_sum(a*b)

In [294]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 280],
       [490, 640]], dtype=int32)>

In [296]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 280],
       [490, 640]], dtype=int32)>